grails-app/domain/com/nutreat/DailyServingsDetail.groovy
package com.nutreat

class DailyServingsDetail implements Comparable {
    FoodGroup foodGroup
    Double amount
    String remarks

    static belongsTo = [dailyServingsHeader: DailyServingsHeader]

    int compareTo(obj) {
        foodGroup.compareTo(obj.foodGroup)
    }

    static constraints = {
        foodGroup blank: false
        amount blank: false
        remarks nullable: true, blank: true
        dailyServingsHeader nullable: false
    }
}

grails-app/controllers/com/nutreat/DailyServingsDetailController.groovy
package com.nutreat

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class DailyServingsDetailController {

    DailyServingsDetailService dailyServingsDetailService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond dailyServingsDetailService.list(params), model:[dailyServingsDetailCount: dailyServingsDetailService.count()]
    }

    def show(Long id) {
        respond dailyServingsDetailService.get(id)
    }

    def create() {
        respond new DailyServingsDetail(params)
    }

    def save(DailyServingsDetail dailyServingsDetail) {
        if (dailyServingsDetail == null) {
            notFound()
            return
        }

        try {
            dailyServingsDetailService.save(dailyServingsDetail)
        } catch (ValidationException e) {
            respond dailyServingsDetail.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail'), dailyServingsDetail.id])
                redirect dailyServingsDetail
            }
            '*' { respond dailyServingsDetail, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond dailyServingsDetailService.get(id)
    }

    def update(DailyServingsDetail dailyServingsDetail) {
        if (dailyServingsDetail == null) {
            notFound()
            return
        }

        try {
            dailyServingsDetailService.save(dailyServingsDetail)
        } catch (ValidationException e) {
            respond dailyServingsDetail.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail'), dailyServingsDetail.id])
                redirect dailyServingsDetail
            }
            '*'{ respond dailyServingsDetail, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        dailyServingsDetailService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/dailyServingsDetail/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-dailyServingsDetail" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-dailyServingsDetail" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.dailyServingsDetail}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.dailyServingsDetail}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.dailyServingsDetail}" method="POST">
                <fieldset class="form">
                    <!-- f:all bean="dailyServingsDetail"/-->
                    <f:field bean="dailyServingsDetail" property="foodGroup" widget-optionValue="name" />
                    <f:field bean="dailyServingsDetail" property="amount" />
                    <f:field bean="dailyServingsDetail" property="remarks" />
                    <f:field bean="dailyServingsDetail" property="dailyServingsHeader" widget-optionValue="kcal" />
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/dailyServingsDetail/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-dailyServingsDetail" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-dailyServingsDetail" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.dailyServingsDetail}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.dailyServingsDetail}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.dailyServingsDetail}" method="PUT">
                <g:hiddenField name="version" value="${this.dailyServingsDetail?.version}" />
                <fieldset class="form">
                    <f:all bean="dailyServingsDetail"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/dailyServingsDetail/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-dailyServingsDetail" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-dailyServingsDetail" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${dailyServingsDetailList}" />

            <div class="pagination">
                <g:paginate total="${dailyServingsDetailCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/dailyServingsDetail/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'dailyServingsDetail.label', default: 'DailyServingsDetail')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-dailyServingsDetail" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-dailyServingsDetail" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <!--f:display bean="dailyServingsDetail" /-->
            <ol class="property-list">
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">Grupo Alimenticio</span>
                    <f:display bean="dailyServingsDetail" property="foodGroup"/>
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">Porciones</span>
                    <div class="property-value"><f:display bean="dailyServingsDetail" property="amount"/></div>
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">Observaciones</span>
                    <div class="property-value"><f:display bean="dailyServingsDetail" property="remarks"/></div>
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">Dieta (Cal)</span>
                    <f:display bean="dailyServingsDetail" property="dailyServingsHeader"/>
                </li>
            </ol>
            <g:form resource="${this.dailyServingsDetail}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.dailyServingsDetail}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>