grails-app/domain/com/nutreat/FoodGroup.groovy
package com.nutreat

class FoodGroup implements Comparable {
    String name
    String remarks

    static hasMany = [food: Food]

    int compareTo(obj) {
        name.compareTo(obj.name)
    }

    static constraints = {
        name blank: false, unique: true
        remarks nullable: true, blank: true
    }
}

grails-app/controllers/com/nutreat/FoodGroupController.groovy
package com.nutreat

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class FoodGroupController {

    FoodGroupService foodGroupService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond foodGroupService.list(params), model:[foodGroupCount: foodGroupService.count()]
    }

    def show(Long id) {
        respond foodGroupService.get(id)
    }

    def create() {
        respond new FoodGroup(params)
    }

    def save(FoodGroup foodGroup) {
        if (foodGroup == null) {
            notFound()
            return
        }

        try {
            foodGroupService.save(foodGroup)
        } catch (ValidationException e) {
            respond foodGroup.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'foodGroup.label', default: 'FoodGroup'), foodGroup.id])
                redirect foodGroup
            }
            '*' { respond foodGroup, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond foodGroupService.get(id)
    }

    def update(FoodGroup foodGroup) {
        if (foodGroup == null) {
            notFound()
            return
        }

        try {
            foodGroupService.save(foodGroup)
        } catch (ValidationException e) {
            respond foodGroup.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'foodGroup.label', default: 'FoodGroup'), foodGroup.id])
                redirect foodGroup
            }
            '*'{ respond foodGroup, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        foodGroupService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'foodGroup.label', default: 'FoodGroup'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'foodGroup.label', default: 'FoodGroup'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/foodGroup/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'foodGroup.label', default: 'FoodGroup')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-foodGroup" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-foodGroup" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.foodGroup}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.foodGroup}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.foodGroup}" method="POST">
                <fieldset class="form">
                    <f:field bean="foodGroup" property="name" />
                    <f:field bean="foodGroup" property="remarks" />
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/foodGroup/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'foodGroup.label', default: 'FoodGroup')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-foodGroup" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-foodGroup" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.foodGroup}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.foodGroup}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.foodGroup}" method="PUT">
                <g:hiddenField name="version" value="${this.foodGroup?.version}" />
                <fieldset class="form">
                    <f:field bean="foodGroup" property="name" />
                    <f:field bean="foodGroup" property="remarks" />
                    <div class='fieldcontain'>
                        <span id="name-label" class="property-label">
                            <b><g:message code="dailyServingsHeader.dailyServingsDetail.label" default="Foods" /></b>
                        </span>
                        <ul style="list-style: none;">
                            <g:each in="${foodGroup.food}" var="food">
                                <li>
                                    <span class="property-value" aria-labelledby="name-label">
                                        <g:link controller="food" action="show" id="${food.id}">${food.name}</g:link>
                                    </span>
                                </li>
                            </g:each>
                            <li>
                                <span class="property-value" aria-labelledby="name-label">
                                    <a href="/food/create?foodGroup.id=${foodGroup.id}">
                                        <g:message code="addFood.label" default="Add food" />
                                    </a>
                                </span>
                            </li>
                        </ul>
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/foodGroup/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'foodGroup.label', default: 'FoodGroup')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-foodGroup" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-foodGroup" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${foodGroupList}" />

            <div class="pagination">
                <g:paginate total="${foodGroupCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/foodGroup/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'foodGroup.label', default: 'FoodGroup')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-foodGroup" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-foodGroup" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <!--f:display bean="foodGroup" /-->
            <ol class="property-list">
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">
                        <g:message code="foodGroup.name.label" default="Grupo Alimenticio" />
                    </span>
                    <div class="property-value"><f:display bean="foodGroup" property="name" /></div>
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">
                        <g:message code="foodGroup.remarks.label" default="Observaciones" />
                    </span>
                    <div class="property-value"><f:display bean="foodGroup" property="remarks" /></div>
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">
                        <g:message code="foodGroup.food.label" default="Alimento" />
                    </span>
                    <f:display bean="foodGroup" property="food"/>
                </li>
            </ol>
            <g:form resource="${this.foodGroup}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.foodGroup}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>