grails-app/domain/com/nutreat/Food.groovy
package com.nutreat

class Food {
    String name
    MeasureUnit measureUnit
    String remarks

    static belongsTo = [foodGroup: FoodGroup]

    static constraints = {
        name blank: false, unique: true
        measureUnit blank: false
        remarks nullable: true, blank: true
        foodGroup nullable: false
    }
}

grails-app/controllers/com/nutreat/FoodController.groovy
package com.nutreat

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class FoodController {

    FoodService foodService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond foodService.list(params), model:[foodCount: foodService.count()]
    }

    def show(Long id) {
        respond foodService.get(id)
    }

    def create() {
        respond new Food(params)
    }

    def save(Food food) {
        if (food == null) {
            notFound()
            return
        }

        try {
            foodService.save(food)
        } catch (ValidationException e) {
            respond food.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'food.label', default: 'Food'), food.id])
                redirect food
            }
            '*' { respond food, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond foodService.get(id)
    }

    def update(Food food) {
        if (food == null) {
            notFound()
            return
        }

        try {
            foodService.save(food)
        } catch (ValidationException e) {
            respond food.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'food.label', default: 'Food'), food.id])
                redirect food
            }
            '*'{ respond food, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        foodService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'food.label', default: 'Food'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'food.label', default: 'Food'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/food/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'food.label', default: 'Food')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-food" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-food" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.food}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.food}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.food}" method="POST">
                <fieldset class="form">
                    <!--f:all bean="food"/-->
                    <f:field bean="food" property="name" />
                    <f:field bean="food" property="measureUnit" widget-optionValue="unit" />
                    <f:field bean="food" property="remarks" />
                    <f:field bean="food" property="foodGroup" widget-optionValue="name" />
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/food/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'food.label', default: 'Food')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-food" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-food" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.food}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.food}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.food}" method="PUT">
                <g:hiddenField name="version" value="${this.food?.version}" />
                <fieldset class="form">
                    <!--f:all bean="food"/-->
                    <f:field bean="food" property="name" />
                    <f:field bean="food" property="measureUnit" widget-optionValue="unit" />
                    <f:field bean="food" property="remarks" />
                    <f:field bean="food" property="foodGroup" widget-optionValue="name" />
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/food/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'food.label', default: 'Food')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-food" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-food" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${foodList}" />

            <div class="pagination">
                <g:paginate total="${foodCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/food/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'food.label', default: 'Food')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-food" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-food" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <!--f:display bean="food" /-->
            <ol class="property-list">
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">
                        <g:message code="food.name.label" default="Alimento" />
                    </span>
                    <div class="property-value"><f:display bean="food" property="name" /></div>
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">
                        <g:message code="food.measureUnit.label" default="Unidad de medida" />
                    </span>
                    <f:display bean="food" property="measureUnit" />
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">
                        <g:message code="food.remarks.label" default="Observaciones" />
                    </span>
                    <div class="property-value"><f:display bean="food" property="remarks" /></div>
                </li>
                <li class="fieldcontain">
                    <span id="name-label" class="property-label">
                        <g:message code="food.foodGroup.label" default="Grupo Alimenticio" />
                    </span>
                    <f:display bean="food" property="foodGroup" />
                </li>
            </ol>
            <g:form resource="${this.food}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.food}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>